modLoader="javafml"
loaderVersion="[47,)"
license="All-Rights-Reserved"
issueTrackerURL="https://github.com/NHblock-Johnsnow/neo-voxy/issues"

[[mods]]
modId="voxy"
version="${version}"
displayName="Neo Voxy"
description="Minecraft 1.20.1 Forge port focused on core Voxy LOD rendering and stability fixes."
authors="Cortex, JohnSnow"
logoFile="assets/voxy/icon.png"

[[dependencies.voxy]]
modId="forge"
mandatory=true
versionRange="[47.3,)"
ordering="NONE"
side="CLIENT"

[[dependencies.voxy]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="CLIENT"

[[dependencies.voxy]]
modId="embeddium"
mandatory=true
versionRange="[0.3.31,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.voxy]]
modId="oculus"
mandatory=false
versionRange="[1.8.0,)"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="client.voxy.mixins.json"

[[mixins]]
config="common.voxy.mixins.json"
